# Generated by Django 3.0 on 2021-12-11 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes_posts')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Categoria')),
            ],
        ),
    ]
