# Generated by Django 3.0 on 2021-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
